sass:
  sass_dir: _sass
  style: compressed
  sourcemap: true;

exclude: [".idea/"]

title: manifest ledger
email: tripathi@vesthq.com
description: "A fintech lab."
keywords: fintech, news, media, affordable, modern, 401(k), retirement, full-service, automated, retirement, pre-tax, auto-enrollment, HR-tech, Fintech, Chicago, Illinois, mobile, compliance, fiduciary, harbor, harborhq, vest, vesthq
url: http://manifestledger.com
repository: https://github.com/VestHQ/manifest_ledger
google_analytics: UA-122835127-1


# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-autoprefixer

autoprefixer:
  browsers:
    - last 10 versions


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
